sudo: required
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - '6.11'


# Should skip the install phase
# install: true

# before_script:
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start
#   - sleep 3

install:
  - npm install
  - node_modules/protractor/bin/webdriver-manager update
  
script:
  - echo "Triggered through push!"
  - gulp unit-test

# after_success:
  # - TRAVIS_MAIN_FOLDER=./travis
  # - TRAVIS_FTP_SCRIPT=$TRAVIS_MAIN_FOLDER/ftp-deployer.sh
  # - chmod ugo+x $TRAVIS_FTP_SCRIPT
  # - $TRAVIS_FTP_SCRIPT


# after_failure
# before_deploy
# deploy
# after_deploy
# after_script
# 
# Deploy phase avoiding to change all the things done during the script intall phases
# deploy:
#   skip_cleanup: true